name: bdsim docker deploy

on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    branches:
      - 'develop'  

jobs:

  docker-bdsim:
    # ensure workflow on runs on main bdsim repo and not forks 
    if: github.repository == 'bdsim-collaboration/bdsim'

    name: Push bdsim docker images to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [alma9-g4.10.7-bdsim, alma9-g4.11.0-bdsim, alma9-g4.11.1-bdsim, alma9-g4.11.2-bdsim, alma9-g4.11.3-bdsim,
                    ubuntu24-g4.10.7-bdsim, ubuntu24-g4.11.0-bdsim, ubuntu24-g4.11.1-bdsim, ubuntu24-g4.11.2-bdsim, ubuntu24-g4.11.3-bdsim]

    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"    
      - name: Check username
        run: |
          echo ${{ vars.BOOGERT_DOCKER_USERNAME }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bdsim/${{ matrix.container }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./building/docker/${{ matrix.container }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}